// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/attendance-app/AttendanceApp.tsx": () => import("../components/mockups/attendance-app/AttendanceApp.tsx")
};
